import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// 根布局中只导入全局样式入口，符合 Next App Router 的 CSS 顺序建议。
// index.css 再按顺序引入 editor/ribbon/dialogs，保证全局样式合并顺序可控。
import './styles/index.css';

// next/font 会在构建时生成字体 CSS 变量。当前 className 暂时注释，
// 但保留变量声明，后续需要启用 Geist 字体时不用重新接入。
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// App Router 的根 layout 必须渲染 <html> 和 <body>。
// 这里保持服务端组件默认形态，交互逻辑全部下放到 app/page.tsx 的 Client Component。
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="min-h-full flex flex-col" id="root">{children}</body>
    </html>
  );
}
